//
//  Places.swift
//  VaCay
//
//  Created by Andre on 8/20/20.
//  Copyright © 2020 VaCay. All rights reserved.
//

import Foundation

class Places {
    
    var items = [String](arrayLiteral:
        "Choose a place type...",
        "Accounting",
        "Airport",
        "Amusement Park",
        "Aquarium",
        "Art Gallery",
        "Atm",
        "Bakery",
        "Bank",
        "Bar",
        "Beauty",
        "Beauty Salon",
        "Bicycle Store",
        "Book Store",
        "Bowling Alley",
        "Bus Station",
        "Cafe",
        "Campground",
        "Car Dealer",
        "Car Rental",
        "Car Wash",
        "Car Repair",
        "Casino",
        "Cemetery",
        "Church",
        "City Hall",
        "Clothing Store",
        "Convenience Store",
        "Courthouse",
        "Dentist",
        "Department Store",
        "Doctor",
        "Electrician",
        "Electronics Store",
        "Embassy",
        "Establishment",
        "Finance",
        "Fire Station",
        "Florist",
        "Food",
        "Funeral Home",
        "Furniture Store",
        "Gas Station",
        "General Contractor",
        "Grocery",
        "Gym",
        "Hair Care",
        "Hardware Store",
        "Health",
        "Hindu Temple",
        "Home Goods Store",
        "Insurance Agency",
        "Jewelry Store",
        "Laundry",
        "Lawyer",
        "Library",
        "Liquor Store",
        "Local Government Office",
        "Locksmith",
        "Lodging",
        "Meal Delivery",
        "Mosque",
        "Movie Rental",
        "Movie Theatre",
        "Moving Company",
        "Museum",
        "Night Club",
        "Painter",
        "Park",
        "Parking",
        "Pet Store",
        "Pharmacy",
        "Physiotherapist",
        "Place Of Worship",
        "Plumber",
        "Police",
        "Post Office",
        "Real Estate Agency",
        "Restaurant",
        "Roofing Contractor",
        "RV Park",
        "School",
        "Shoe Store",
        "Shopping Mall",
        "Spa",
        "Stadium",
        "Storage",
        "Store",
        "Subway Station",
        "Synagogue",
        "Taxi Stand",
        "Train Station",
        "Travel Agency",
        "Veterinary Care",
        "Zoo"
    )
    
}
